### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Cyberking99** [dragon-language-projects/dragon-core#11]
**Describe the bug**
Dragon 1.9.6 and Dragon 1.9.7 not installing in Linux.

**To Reproduce**
1. Download the compressed file from here: Dragon 1.9.6 'https://dragon-lang.org/dragon196' or Dragon 1.9.7 'https://dragon-lang.org/dragon197'
2. Extract the compressed file
3. Open your terminal in the extracted file directory and install using 'bash install.sh'
4. Now, run 'dragon -sh'
5. Output is: "Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.                                                                                                                    
Error: A fatal exception has occurred. Program will exit."

**Expected behavior**
"Welcome to Dragon <version> (1.9.6 or 1.9.7) Shell
Type in expressions to have them evaluated.
  :help - show help     :reset - clear buffer
  :exit - exit REPL    
"
**Desktop (please complete the following information):**
 - OS: [e.g. Kali Linux]
 - Version [e.g. 2020.1]

**Comment by ghost** [comment]
Thank you
